services:
  slmcmsdashboard:
    # Use your Docker image name here
    image: goswamirohit/slmcmsdashboard:v8
    container_name: slmcmsdashboard
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:3000"
    # This is the key line that tells Docker to read the variables from the .env file
    env_file:
      - .env
      - .env.local